-- =============================================================================
-- The Vault — Dashboard Security Hardening
-- =============================================================================
-- Run this ONCE in the Supabase SQL editor, AFTER supabase-dashboard-setup.sql:
--   https://supabase.com/dashboard/project/mopjzwjyiiwzovoeybcn/sql/new
--
-- Creates the login_attempts table used for:
--   1. Rate limiting  — blocks brute-force after 10 fails in 15 min per IP
--   2. Audit logging  — lets you see every login attempt from the dashboard
--                       (add a query for this later if you want to surface it)
--
-- Row Level Security is enabled with NO policies, which means only the
-- service-role key (used server-side by lib/auth.ts) can read or write this
-- table. The browser cannot touch it at all.
-- =============================================================================

create table if not exists public.login_attempts (
  id            bigint generated by default as identity primary key,
  ip            text not null,
  success       boolean not null,
  attempted_at  timestamptz not null default now()
);

-- Composite index matches the WHERE clause in checkRateLimit():
--   WHERE ip = ? AND success = false AND attempted_at >= ?
create index if not exists login_attempts_ip_time_idx
  on public.login_attempts (ip, attempted_at desc)
  where success = false;

-- Full ordered index for the audit log view (see every attempt, newest first).
create index if not exists login_attempts_time_idx
  on public.login_attempts (attempted_at desc);

alter table public.login_attempts enable row level security;

-- NO policies = nothing except the service-role key can read/write.
-- If you ever see a row appear that shouldn't, that's a service-key leak.

-- =============================================================================
-- Optional housekeeping: purge records older than 30 days. The rate-limit
-- query only looks at the last 15 minutes, and you probably don't need
-- attempt history from months ago. Run manually or schedule with pg_cron.
-- =============================================================================
--
-- delete from public.login_attempts
-- where attempted_at < now() - interval '30 days';
