-- =============================================================================
-- The Vault — Owner Dashboard: Supabase Setup
-- =============================================================================
-- Run this entire file ONCE in the Supabase SQL editor:
--   https://supabase.com/dashboard/project/mopjzwjyiiwzovoeybcn/sql/new
--
-- It will:
--   1. Create the `page_views` table for visit analytics
--   2. Enable Row Level Security on `waitlist` and `page_views`
--   3. Allow the public site to INSERT new signups + visits
--   4. BLOCK the public from ever reading signups or visits
--   5. Let the dashboard read them by using the service-role key (server-only)
-- =============================================================================

-- ---------- 1. page_views table ---------------------------------------------
create table if not exists public.page_views (
  id          bigint generated by default as identity primary key,
  path        text not null,
  created_at  timestamptz not null default now()
);

create index if not exists page_views_created_at_idx
  on public.page_views (created_at desc);

-- ---------- 2. Lock down waitlist -------------------------------------------
alter table public.waitlist enable row level security;

drop policy if exists "Anyone can join waitlist" on public.waitlist;
create policy "Anyone can join waitlist"
  on public.waitlist
  for insert
  to anon
  with check (true);

-- No SELECT policy for anon/public = nobody can read it from the browser.
-- Service role bypasses RLS, so the dashboard still works.

-- ---------- 3. Lock down page_views -----------------------------------------
alter table public.page_views enable row level security;

drop policy if exists "Anyone can log a page view" on public.page_views;
create policy "Anyone can log a page view"
  on public.page_views
  for insert
  to anon
  with check (true);

-- Same deal: no SELECT policy = public can't read visit history.

-- =============================================================================
-- Done. Verify in the Table Editor that both tables show "RLS enabled".
-- Now head back to the app and fill in SUPABASE_SERVICE_ROLE_KEY in .env.local.
-- =============================================================================
